using Microsoft.Agents.AI;
using Microsoft.Extensions.AI;
using OpenAI.Responses;

namespace dotnet_ai_agent_sample;

internal class Agent_Step21_WebSearch
{
    public async Task Run()
    {
        var envSetting = new EnvSetting();
        // Create a ConversationClient directly from OpenAIClient
        var openAIClient = envSetting.GetChatClient();

        const string AgentInstructions = "You are a helpful assistant that can search the web to find current information and answer questions accurately.";
        const string AgentName = "WebSearchAgent-RAPI";

        // Create a AIAgent with HostedWebSearchTool.
        AIAgent agent = openAIClient
            .AsAIAgent(instructions: AgentInstructions,
            name: AgentName,
            tools: [new HostedWebSearchTool()]);

        AgentResponse response = await agent.RunAsync("What's the weather today in Seattle?");

        // Get the text response
        Console.WriteLine($"Response: {response.Text}");

        // Getting any annotations/citations generated by the web search tool
        foreach (AIAnnotation annotation in response.Messages.SelectMany(m => m.Contents).SelectMany(c => c.Annotations ?? []))
        {
            Console.WriteLine($"Annotation: {annotation}");
            if (annotation.RawRepresentation is UriCitationMessageAnnotation urlCitation)
            {
                Console.WriteLine($$"""
        Title: {{urlCitation.Title}}
        URL: {{urlCitation.Uri}}
        """);
            }
        }

    }
}
